apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: predictive-hpa
  namespace: predictive
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-flask
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: predicted_replicas
      target:
        type: AverageValue
        averageValue: 3
